In [1]:
### Sesstion 25: Text Summarization (In-Class Assignment)
# Since covering this topic within one session is not enough, every individual will work on this text summarization model together within today's session.
# Note that this will be considered as the last assignment, everyone must submit their work at the end of the class to earn credits.

import numpy as np
import gensim
from urllib.request import urlretrieve, urlopen
import gzip
import zipfile

In [2]:
#connect Colab to your Google Drive.
from google.colab import drive
import os
drive.mount('/content/gdrive')


Mounted at /content/gdrive


In [3]:
# We will use Glove, a pre-trained word embedding vectors.
urlretrieve("http://nlp.stanford.edu/data/glove.6B.zip", filename="glove.6B.zip")
zf = zipfile.ZipFile('glove.6B.zip')
zf.extractall()
zf.close()

In [4]:
# Glove comes in multiple different formats based on different dimension legnth. We will use 50 (Not 100) dimension Glove vector.
glove_dict = dict()
f = open('glove.6B.50d.txt', encoding="utf8")

for line in f:
    word_vector = line.split()
    word = word_vector[0]
    word_vector_arr = np.asarray(word_vector[1:], dtype='float32')
    glove_dict[word] = word_vector_arr
f.close()


In [5]:
# For each word which exists in the file, it is represented with 50 different real numbers.
# print out the embedding vector for the word 'pizza'.
print (glove_dict['pizza'])

[ 0.62143   -0.49645   -0.69599    0.19473    1.0616     0.14227
 -0.79524    0.19404    0.0071687  0.14646   -0.61261    0.0037311
  0.41935    1.0381     0.16911   -0.53342   -0.52508    0.79629
 -0.029128  -0.44912    1.0138    -0.59214    0.17643    1.5506
 -0.96916   -0.42896   -0.92664    0.43301    1.2915    -0.80836
  1.336      0.24572   -0.11799    2.0015    -0.27431    0.17803
 -0.31508    0.84582    0.77419    0.45243    0.73485    0.44473
 -0.77466    0.43471    0.53486    0.98216   -0.70731   -0.48557
  0.16453    0.65013  ]


In [ ]:
## We will work on generating "sentence" embedding (not word embedding).

# Assume that you have 10 different sentences and you want to compare these to each other.

# Convert each sentence to a vector (in the same vector length) and perform such as cosine similarity:
  # How to convert each sentence to a sentence embedding vector?
  # Compute the average of word embedding vectors per sentence (These words exist in that sentence).

# Note that cosine similarity tutorial in the past was based on word-level tf-idf vectors & not related to embedding.

In [6]:
# For OOV (the words which exist in a data set but do not exist in the Glove vector), generate a 50-length of zero embedding vector.
embedding_dim = 50
zero_vector = np.zeros(embedding_dim)
print (zero_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


In [7]:
# convert each word into embedding vector & convert OOV into zero embedding vector.
# Compute the average of the word embedding vectors -> sentence embedding vector.

def calculate_sentence_vector(sentence):
  return sum([glove_dict.get(word, zero_vector) for word in sentence])/len(sentence)

In [8]:
eng_sent = ['pizza']
sentence_vector = calculate_sentence_vector(eng_sent)
print(len(sentence_vector))
print (sentence_vector)

50
[ 0.62143   -0.49645   -0.69599    0.19473    1.0616     0.14227
 -0.79524    0.19404    0.0071687  0.14646   -0.61261    0.0037311
  0.41935    1.0381     0.16911   -0.53342   -0.52508    0.79629
 -0.029128  -0.44912    1.0138    -0.59214    0.17643    1.5506
 -0.96916   -0.42896   -0.92664    0.43301    1.2915    -0.80836
  1.336      0.24572   -0.11799    2.0015    -0.27431    0.17803
 -0.31508    0.84582    0.77419    0.45243    0.73485    0.44473
 -0.77466    0.43471    0.53486    0.98216   -0.70731   -0.48557
  0.16453    0.65013  ]


In [9]:
eng_sent = ['restaurant']
sentence_vector = calculate_sentence_vector(eng_sent)
print(len(sentence_vector))
print (sentence_vector)

50
[ 0.69607    0.42922   -1.0206     0.20534    0.94613   -0.8808
 -1.391     -0.063854   0.20051    0.067331  -0.69957   -0.44104
  0.41343    0.98698    0.48247   -0.20524    0.015262   0.81055
 -0.16189   -0.57772    1.4103     0.30844   -0.84441    1.4506
 -0.78245   -0.79539   -0.67531    0.87824    0.32835   -0.36903
  2.0142    -0.30928    0.078092   0.97173    0.33983    0.10481
  0.15796    0.5853     0.79749    0.4152     0.22678    0.53758
  0.0064708  0.060384   0.57345    0.28672   -0.91732   -0.74019
  0.81009    0.85844  ]


In [10]:
# If the below eng_sent is a sentence which contains 'cat' and 'god'.
eng_sent = ['pizza','restaurant']
sentence_vector = calculate_sentence_vector(eng_sent)
print(len(sentence_vector))
print (sentence_vector)

50
[ 0.65875    -0.03361501 -0.85829496  0.200035    1.003865   -0.36926502
 -1.09312     0.065093    0.10383935  0.1068955  -0.65609    -0.21865445
  0.41639     1.01254     0.32579    -0.36933002 -0.254909    0.80341995
 -0.095509   -0.51342     1.21205    -0.14185001 -0.33399     1.5006001
 -0.875805   -0.612175   -0.80097497  0.655625    0.80992496 -0.588695
  1.6751     -0.03178    -0.019949    1.486615    0.03276001  0.14142
 -0.07855999  0.71556     0.78584003  0.433815    0.480815    0.49115503
 -0.3840946   0.247547    0.554155    0.63444    -0.812315   -0.61288
  0.48731     0.754285  ]


In [ ]:
# OOV -> zero vector
eng_sent = ['asdfdsafadsf']
sentence_vector = calculate_sentence_vector(eng_sent)
print(len(sentence_vector))
print (sentence_vector)

50
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


In [11]:
import numpy as np
import re
import pandas as pd
import matplotlib.pyplot as plt
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords
from urllib.request import urlretrieve
import zipfile
from sklearn.metrics.pairwise import cosine_similarity
import networkx as nx


In [12]:
#load a stop-word set.
import nltk
nltk.download('stopwords')
stop_words = stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [13]:
#download a data set that I have uploaded.
data = pd.read_csv("/content/gdrive/MyDrive/Baruch CUNY/Bruh Senior Year/Fall 2023/CIS 4120 - NLP/Assignment 5/news_samples.csv")
print (data.shape)

(2, 3)


In [14]:
print (data)

                                       news_contents  \
0   U.S. economy is the envy of the world. It's o...   
1  wall Street analysts are increasingly bullish ...   

                                            headline  news_id  
0  America Is the Richest Country, but Americans ...        1  
1  Deutsche Bank, Bank of America Predict Stocks ...        2  


## (1) The original text (news_contents) should be tokenized at a sentence-level.

In [15]:
import nltk
nltk.download('punkt')

# We will use "news_contents".
# sentence tokenization -> "Setences" column (multiple sentences for each row of "news_contents").

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

## (2) For each sentence within the original text (news_contents), perform word-tokenize. Also, apply pre-processings such as lower-casing & removing stop-words.

In [16]:
# word-tokenize
data['sentences'] = data['news_contents'].apply(sent_tokenize)

def word_tk(sentences):
    return [word_tokenize(sentence) for sentence in sentences]

data['sentences_tk'] = data['sentences'].apply(word_tk)

# pre-processing

def preprocess_sentence(sentence):
  # words only, lower case
  sentence = [re.sub(r'[^a-zA-z\s]', '', word).lower() for word in sentence]
  # remove stop-words
  return [word for word in sentence if word not in stop_words and word]

def pre_proc_apply(sentences):
  return [preprocess_sentence(sentence) for sentence in sentences]

data['sentences_tk'] = data['sentences_tk'].apply(pre_proc_apply)

print(data.shape)
data.head()

(2, 5)


news_contents  \
0   U.S. economy is the envy of the world. It's o...   
1  wall Street analysts are increasingly bullish ...   

                                            headline  news_id  \
0  America Is the Richest Country, but Americans ...        1   
1  Deutsche Bank, Bank of America Predict Stocks ...        2   

                                           sentences  \
0  [ U.S. economy is the envy of the world., It's...   
1  [wall Street analysts are increasingly bullish...   

                                        sentences_tk  
0  [[us, economy, envy, world], [track, produce, ...  
1  [[wall, street, analysts, increasingly, bullis...

In [ ]:
# We will use "news_contents".
# sentence tokenization -> "Setences" column (multiple sentences for each row of "news_contents").
#                       -> apply word-tokenization & pre-processings -> "tokenized_sentences" column.

In [17]:
# For OOV (the words which exist in a data set but do not exist in the Glove vector), generate a 50-length of zero embedding vector.
embedding_dim = 50
zero_vector = np.zeros(embedding_dim)

## (3) Convert each word into embedding vector, then generate sentence-level embedding vectors.

*   Words that are present within the pre-trained Glove -> convert the words into embedding vectors.
*   Words that are not present within the Glove (OOV) & other cases (i.e. sentence becomes 0 after removing stop-words) -> convert these into zero vectors.



In [18]:
# convert each word into embedding vector & convert OOV into zero embedding vector & others such as a sentence has 0 length after removing stop-words.
# Compute the average of the word embedding vectors -> sentence embedding vector.

def calculate_sentence_vector(sentence):
  if len(sentence) != 0:
    return sum([glove_dict.get(word, zero_vector)
                  for word in sentence])/len(sentence)
  else:
    return zero_vector

# data['sentences_emb'] = data['sentences_tk'].apply(lambda x: [calculate_sentence_vector(sentence) for sentence in data['sentences_tk']])

def sentences_to_vectors(sentences):
    return [calculate_sentence_vector(sentence) for sentence in sentences]

data['sentences_emb'] = data['sentences_tk'].apply(sentences_to_vectors)

print(data.shape)
data.head()

(2, 6)


news_contents  \
0   U.S. economy is the envy of the world. It's o...   
1  wall Street analysts are increasingly bullish ...   

                                            headline  news_id  \
0  America Is the Richest Country, but Americans ...        1   
1  Deutsche Bank, Bank of America Predict Stocks ...        2   

                                           sentences  \
0  [ U.S. economy is the envy of the world., It's...   
1  [wall Street analysts are increasingly bullish...   

                                        sentences_tk  \
0  [[us, economy, envy, world], [track, produce, ...   
1  [[wall, street, analysts, increasingly, bullis...   

                                       sentences_emb  
0  [[-0.095894754, 0.2611, 0.5079025, -0.02308924...  
1  [[-0.001157279, 0.075452566, 0.46483308, 0.017...

In [33]:
print(data['sentences_tk'][0])
print(len(data['sentences'][0]))
print(len(data['sentences_tk'][0]))
print(len(data['sentences_emb'][0]))

[['us', 'economy', 'envy', 'world'], ['track', 'produce', 'nearly', 'trillion', 'goods', 'services', 'year', 'making', 'wealthiest', 'measured', 'annual', 'gross', 'domestic', 'product'], ['china', 'billion', 'people', 'fairly', 'distant', 'second', 'us', 'quarter', 'population'], ['despite', 'lingering', 'inflation', 'rising', 'interest', 'rates', 'forecasts', 'recession', 'us'], ['gross', 'domestic', 'product', 'gdp', 'exploded', 'third', 'quarter', 'thanks', 'goldilocks', 'economy', 'buoyed', 'national', 'tours', 'beyonc', 'taylor', 'swift', 'movie', '``', 'barbie'], ['gdp', 'value', 'goods', 'services', 'produced', 'specific', 'time', 'period'], ['whether', 'nation', 'annual', 'gdp', 'growing', 'shrinking', 'economists', 'define', 'economic', 'booms', 'recessions'], ['nation', 'gdp', 'came', 'sizzling', 'commerce', 'department', 'bureau', 'economic', 'analysis', 'reported', 'wednesday'], ['economists', 'expect', 'economic', 'growth', 'drastically', 'slow', 'final', 'months', 'year'

In [ ]:
# We will use "news_contents".
# sentence tokenization -> "Setences" column (multiple sentences for each row of "news_contents").
#                       -> apply word-tokenization & pre-processings
#                       -> "tokenized_sentences" column.
#                       -> each sentence should be converted to a sentence embedding vector -> "SentenceEmbedding" column.

## (4) perform cosine similiarity among all the sentences (embedded vectors) for each news article.

In [28]:
# perform consine similiarity for all the available sentences per article.

def similarity_matrix(sentence_embedding):
  sim_mat = np.zeros([len(sentence_embedding), len(sentence_embedding)])
  for i in range(len(sentence_embedding)):
      for j in range(len(sentence_embedding)):
        sim_mat[i][j] = cosine_similarity(sentence_embedding[i].reshape(1, embedding_dim),
                                          sentence_embedding[j].reshape(1, embedding_dim))[0,0]
  return sim_mat

data['SimMatrix'] = data['sentences_emb'].apply(similarity_matrix)

print (data.shape)
data.head()

(2, 7)


news_contents  \
0   U.S. economy is the envy of the world. It's o...   
1  wall Street analysts are increasingly bullish ...   

                                            headline  news_id  \
0  America Is the Richest Country, but Americans ...        1   
1  Deutsche Bank, Bank of America Predict Stocks ...        2   

                                           sentences  \
0  [ U.S. economy is the envy of the world., It's...   
1  [wall Street analysts are increasingly bullish...   

                                        sentences_tk  \
0  [[us, economy, envy, world], [track, produce, ...   
1  [[wall, street, analysts, increasingly, bullis...   

                                       sentences_emb  \
0  [[-0.095894754, 0.2611, 0.5079025, -0.02308924...   
1  [[-0.001157279, 0.075452566, 0.46483308, 0.017...   

                                           SimMatrix  
0  [[1.0000001192092896, 0.7950466871261597, 0.84...  
1  [[1.000000238418579, 0.9066437482833862, 0.863...

In [35]:
print((data['SimMatrix'][0]))

[[1.00000012 0.79504669 0.84893715 ... 0.84197044 0.84388942 0.86147678]
 [0.79504669 1.         0.90504944 ... 0.91524291 0.90860027 0.93349896]
 [0.84893715 0.90504944 0.99999988 ... 0.94176066 0.92819795 0.95396477]
 ...
 [0.84197044 0.91524291 0.94176066 ... 0.99999994 0.90411524 0.94597489]
 [0.84388942 0.90860027 0.92819795 ... 0.90411524 1.         0.97754467]
 [0.86147678 0.93349896 0.95396477 ... 0.94597489 0.97754467 1.        ]]


## (5) For the 2nd article:

*   What is the number of sentences?
*   You Answer: 14 (given)

*   What is the shape of the sentence embedded vectors? Explain why the shape becomes x and y?
*   You Answer: x, y
*   Explain:

*   What is the shape of the cosine similiarity matrix? Explain why the shape becomes x and y?
*   You Answer: x, y
*   Explain:







In [ ]:
# What is the number of sentences
print("What is the number of sentences in the 2nd article?:")
print(f'The number of sentences in the 2nd article is: {len(data["sentences"][1])}\n')

# What is the shape of the sentence embedded vectors? Explain why the shape becomes x and y?
print("What is the shape of the sentence embedded vectors? Explain why the shape becomes x and y?")
print(f"The shape of the sentence embedded vectors is: {len(data['sentences_emb'][1]), len(data['sentences_emb'][1][0])}")
print("The reason the shape of the embedded vectors column is (14,50) is because there are 14 total sentences, so 14 total embedding vectors\n\
each with 50 entries as we set our embedding dimensions as 50 earlier with the line: embedding_dim = 50 .\n")

# What is the shape of the cosine similiarity matrix? Explain why the shape becomes x and y?
print("What is the shape of the cosine similiarity matrix? Explain why the shape becomes x and y?")
print(f'The shape of the cosine similarity matrix for the 2nd article is: {data["SimMatrix"][1].shape}')
print('The reason the shape of the similarity matrix is (14, 14) is because the purpose of the matrix is to compare each sentence in in article 2\n\
against eacher other. So since there are 14 total sentences, it will compare sentence_1 first against itself, then against sentence_2, sentence_3,\n\
. . . , all the way to sentence_n which in this case is the 14th sentence.\n')

What is the number of sentences in the 2nd article?:
The number of sentences in the 2nd article is: 14

What is the shape of the sentence embedded vectors? Explain why the shape becomes x and y?
The shape of the sentence embedded vectors is: (14, 50)
The reason the shape of the embedded vectors column is (14,50) is because there are 14 total sentences, so 14 total embedding vectors
each with 50 entries as we set our embedding dimensions as 50 earlier with the line: embedding_dim = 50 .

What is the shape of the cosine similiarity matrix? Explain why the shape becomes x and y?
The shape of the cosine similarity matrix for the 2nd article is: (14, 14)
The reason the shape of the similarity matrix is (14, 14) is because the purpose of the matrix is to compare each sentence in in article 2
against eacher other. So since there are 14 total sentences, it will compare sentence_1 first against itself, then against sentence_2, sentence_3,
. . . , all the way to sentence_n which in this case is 

In [ ]:
# PageRank computes a ranking of the nodes in a network graph based on the structure of the incoming links.
# It was originally designed as an algorithm to rank web pages.

def calculate_score(sim_matrix):
    nx_graph = nx.from_numpy_array(sim_matrix)
    scores = nx.pagerank(nx_graph)
    return scores


In [ ]:
#Using a simple example, it shows how PageRank model can be applied to the example.
a = [[0, 0.5, 0, 0.5], [0.5, 0, 0.5, 0], [0.25,0.25, 0.25, 0.25],[1, 0, 0, 0]]
array_a = np.array(a)
print (array_a)

[[0.   0.5  0.   0.5 ]
 [0.5  0.   0.5  0.  ]
 [0.25 0.25 0.25 0.25]
 [1.   0.   0.   0.  ]]


In [ ]:
calculate_score(array_a)

{0: 0.3547023094010009,
 1: 0.17014942326864738,
 2: 0.21885646210522575,
 3: 0.25629180522512585}

## (6) Compute "Final Score" just like the above based on the cosine similiarity score you have derived and add the "Final Score" as an another column.

In [ ]:
data['Final_Score'] = data['SimMatrix'].apply(calculate_score)

print(data['Final_Score'][0])
print(data['Final_Score'][1])

{0: 0.028088700136929455, 1: 0.03029964209049045, 2: 0.030084259696337733, 3: 0.027404363490126073, 4: 0.029093252336287144, 5: 0.029237042584097345, 6: 0.02839530805874515, 7: 0.028463585049670843, 8: 0.029785273204895095, 9: 0.030038858215783497, 10: 0.029399779220915218, 11: 0.02937105180491214, 12: 0.030220887801092784, 13: 0.02897625898142405, 14: 0.02667656793962516, 15: 0.02958549576788856, 16: 0.030419885612470686, 17: 0.02730249067816025, 18: 0.028263021137235514, 19: 0.028029231984412498, 20: 0.026560165225501496, 21: 0.02950057443555084, 22: 0.02917172444378141, 23: 0.029075833641225353, 24: 0.02406600016648889, 25: 0.02913149444181374, 26: 0.029188598642419412, 27: 0.018268275959806027, 28: 0.02898866475979605, 29: 0.027082344889698094, 30: 0.02592901789587275, 31: 0.004267432626816852, 32: 0.029415345354060415, 33: 0.030014716669167232, 34: 0.029853810780746136, 35: 0.030351044275755606}
{0: 0.07391710581732433, 1: 0.07384922936928719, 2: 0.06880632500682694, 3: 0.07298374

## (7) Based on the highest score values, choose 3 highest scored sentences and consider these sentences as a summary output per article.

In [ ]:
def ranked_sentences(sentences, scores, n=3):
    # sort the score from the highest to the lowest.
    top_scores = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)
    # choose the corresponding sentences.
    top_n_sentences = [sentence for score,sentence in top_scores[:n]]
    # put these sentences into a single paragraph.
    return " ".join(top_n_sentences)


data['summary'] = data.apply(lambda x: ranked_sentences(x.sentences, x.Final_Score), axis=1)

print (data.shape)
data.head()

(2, 9)


news_contents  \
0   U.S. economy is the envy of the world. It's o...   
1  wall Street analysts are increasingly bullish ...   

                                            headline  news_id  \
0  America Is the Richest Country, but Americans ...        1   
1  Deutsche Bank, Bank of America Predict Stocks ...        2   

                                           sentences  \
0  [ U.S. economy is the envy of the world., It's...   
1  [wall Street analysts are increasingly bullish...   

                                        sentences_tk  \
0  [[us, economy, envy, world], [track, produce, ...   
1  [[wall, street, analysts, increasingly, bullis...   

                                       sentences_emb  \
0  [[-0.095894754, 0.2611, 0.5079025, -0.02308924...   
1  [[-0.001157279, 0.075452566, 0.46483308, 0.017...   

                                           SimMatrix  \
0  [[1.0000001192092896, 0.7950466871261597, 0.84...   
1  [[1.000000238418579, 0.9066437482833862, 0.863...   

                                         Final_Score  \
0  {0: 0.028088700136929455, 1: 0.030299642090490...   
1  {0: 0.07391710581732433, 1: 0.0738492293692871...   

                                             summary  
0  Another way economists gauge the wealth of nat...  
1  “We expect 2024 to be the year when central ba...

## (8) Let's check the original article and its summary output for the 2nd sample. Show your outputs.

In [ ]:
# Let's check the original article and its summary output for the 2nd sample.
print('Article Num',2)
print()
print()
print('original article :\n\n',data.iloc[1,0])
print()
print()
print('summarized output :\n\n',data.iloc[1,8])
print()
print()

Article Num 2


original article :

 wall Street analysts are increasingly bullish on the S&P’s 500 performance over the next year, predicting it will eclipse its record set in January 2022.

Strategists at Deutsche Bank Group, headed by Bankim "Binky" Chadha, are expecting the index to reach 5,100 points by the end of 2024 as inflation slows and companies post strong earnings, they said in a research note reported by Bloomberg. That's almost 12% up from where it's currently trading, at around 4,557 points.

“Despite above-trend growth, core inflation has fallen,” the strategists wrote. “Continued declines would return inflation to its pre-pandemic range without requiring slower growth.” Because a recession “is widely anticipated and expected to be mild and short” the strategists predict a modest and brief selloff. The projections suggest an approximately 12% increase in the S&P 500 from today's levels. The S&P 500 hit its all-time record of 4,796.56 in early January 2022.

BofA Global